import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

interface QuoteData {
    id: string;
    clientName: string;
    items: string[];
    estimatedPrice?: number;
}

/**
 * Generate a PDF for a Quote (Draft or Final)
 * @param quoteData - Data for the quote
 * @param isFinal - If true, includes price. If false, shows TBD.
 * @returns Path to the generated PDF file
 */
export async function generateQuotePDF(quoteData: QuoteData, isFinal: boolean = false): Promise<string> {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });

            // Ensure temp directory exists
            const tempDir = path.join(process.cwd(), 'public', 'temp');
            if (!fs.existsSync(tempDir)) {
                fs.mkdirSync(tempDir, { recursive: true });
            }

            const filename = isFinal
                ? `Quote_Final_${quoteData.id}.pdf`
                : `Spec_Sheet_${quoteData.id}.pdf`;

            const filePath = path.join(tempDir, filename);
            const writeStream = fs.createWriteStream(filePath);

            doc.pipe(writeStream);

            // --- HEADER ---
            // Add Logo if available (placeholder for now)
            // doc.image('public/logo.png', 50, 45, { width: 50 });

            doc.fillColor('#444444')
                .fontSize(20)
                .text('SERA AUTO SOLUTIONS', 50, 57, { align: 'center' })
                .moveDown();

            doc.fontSize(10)
                .text('Automated Web & AI Solutions', { align: 'center' })
                .moveDown();

            // --- DIVIDER ---
            doc.moveTo(50, 130).lineTo(550, 130).stroke();

            // --- CLIENT INFO ---
            doc.moveDown();
            doc.fontSize(12).fillColor('black').text(`Client: ${quoteData.clientName}`);
            doc.text(`Project ID: ${quoteData.id}`);
            doc.text(`Date: ${new Date().toLocaleDateString()}`);

            // --- REQUIREMENTS ---
            doc.moveDown();
            doc.fontSize(14).text('Project Requirements / Scope of Work', { underline: true });
            doc.moveDown();

            quoteData.items.forEach(item => {
                doc.fontSize(12).text(`• ${item}`, { indent: 20 });
                doc.moveDown(0.5);
            });

            // --- PRICE SECTION ---
            doc.moveDown(2);
            doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
            doc.moveDown();

            if (isFinal && quoteData.estimatedPrice) {
                // Final Version for Client
                doc.fontSize(16).fillColor('green')
                    .text(`TOTAL ESTIMATE: LKR ${quoteData.estimatedPrice.toLocaleString()}.00`, { align: 'right' });

                doc.moveDown();
                doc.fontSize(10).fillColor('gray')
                    .text('This quotation is valid for 14 days.', { align: 'right' });

                // --- PERFORMANCE CLAUSE ---
                doc.moveDown(2);
                doc.fontSize(10).fillColor('black')
                    .text('Clause 8.1: By transferring the 40% Advance Payment, the Client acknowledges that they have read, understood, and agreed to the terms of this proposal. A physical signature is not required for validity.', { width: 500 });

                // --- SIGNATURE ---
                doc.moveDown(2);
                const sigPath = path.join(process.cwd(), 'assets', 'agency_signature.png');
                if (fs.existsSync(sigPath)) {
                    doc.image(sigPath, 400, doc.y, { width: 150 });
                    doc.moveDown();
                }
                doc.fontSize(12).text('Authorized Signature', 400, doc.y + 10);
                doc.fontSize(10).text(`Date: ${new Date().toLocaleDateString()}`, 400, doc.y + 25);

            } else {
                // Draft Version for Developer
                doc.fontSize(16).fillColor('red')
                    .text(`PRICE: PENDING ESTIMATION (TBD)`, { align: 'right' });

                doc.moveDown();
                doc.fontSize(10).fillColor('gray')
                    .text('Internal Document - Waiting for Developer Validation', { align: 'right' });

                // --- DRAFT WATERMARK ---
                doc.save();
                doc.rotate(45, { origin: [300, 400] });
                doc.fontSize(100).fillColor('red').opacity(0.1).text('DRAFT', 100, 300);
                doc.restore();

                doc.moveDown(2);
                doc.fontSize(12).fillColor('red').text('PENDING APPROVAL - NOT VALID', 400, doc.y);
            }

            // --- FOOTER ---
            const bottom = doc.page.height - 50;
            doc.fontSize(10).fillColor('gray')
                .text('Generated by Sera AI Agent', 50, bottom, { align: 'center', width: 500 });

            doc.end();

            writeStream.on('finish', () => {
                resolve(filePath);
            });

            writeStream.on('error', (err) => {
                reject(err);
            });

        } catch (error) {
            reject(error);
        }
    });
}
